version: '3'
services: 
      frontend: 
          container_name: realtime_frontend
          build: 
            context: ./client
            dockerfile: Dockerfile
          image: ferdy/realtime_frontend
          ports: 
            - "3000:3000"
          volumes: 
            - ./client:/usr/src/app
      backend:
          container_name: realtime_backend
          build: 
            context: ./server
            dockerfile: Dockerfile
          image: ferdy/realtime_backend
          ports: 
            - "5000:5000"
          volumes: 
            - ./server:/usr/src/app